# Analysis of football data from 1999 - 2024

1. import necessary data libraries

In [121]:
# import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

2. create class for data inspection

In [122]:
# create classmethod to load data
class FootballData:
    def __init__(self, file_path):
        self.file_path = file_path

    def load_data(self):
        return pd.read_csv(self.file_path)
    
    def inspect_data(self):
        return self.load_data().head()
    
    def describe_data(self):
        return self.load_data().describe()
    
# create instance of FootballData
football_data = FootballData('/home/sirian/Documents/AI_Agents_&_LLMS/Cursor/sirian/data/match_statistics.csv')

# load data
football_data.load_data()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HO,AO,HY,AY,HR,AR,HBP,ABP,Time,AHh
0,E0,1999-08-07,Arsenal,Leicester,2.0,1.0,H,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,1999-08-07,Chelsea,Sunderland,4.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,1999-08-07,Coventry,Southampton,0.0,1.0,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,1999-08-07,Leeds,Derby,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,1999-08-07,Middlesbrough,Bradford,0.0,1.0,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9165,E0,2024-09-21,Southampton,Ipswich,1.0,1.0,D,1.0,0.0,H,...,NaN,NaN,4.0,4.0,0.0,0.0,NaN,NaN,15:00:00,-0.25
9166,E0,2024-09-21,Tottenham,Brentford,3.0,1.0,H,2.0,1.0,H,...,NaN,NaN,3.0,1.0,0.0,0.0,NaN,NaN,15:00:00,-1.00
9167,E0,2024-09-21,Crystal Palace,Man United,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,3.0,1.0,0.0,0.0,NaN,NaN,17:30:00,0.25
9168,E0,2024-09-22,Brighton,Nott'm Forest,2.0,2.0,D,2.0,1.0,H,...,NaN,NaN,3.0,4.0,0.0,1.0,NaN,NaN,14:00:00,-0.75
9169,E0,2024-09-22,Man City,Arsenal,2.0,2.0,D,1.0,2.0,A,...,NaN,NaN,3.0,4.0,0.0,1.0,NaN,NaN,16:30:00,-0.75

In [123]:
# create function to describe the data

def inspect_data(df):
    """
    Inspect the dataframe: print shape, missing values, and description.
    """
    print("Shape of data:", df.shape)
    print("\nMissing values per column:\n", df.isnull().sum())
    # print("\nData description:\n", df.describe(include='all'))

# Example usage:
df = football_data.load_data()
inspect_data(df)

Shape of data: (9170, 32)

Missing values per column:
 Div              0
Date             0
HomeTeam         0
AwayTeam         0
FTHG             0
FTAG             0
FTR              0
HTHG             0
HTAG             0
HTR              0
Attendance    8411
Referee        380
HS             380
AS             380
HST            380
AST            380
HHW           8410
AHW           8410
HC             380
AC             380
HF             380
AF             380
HO            8410
AO            8410
HY             380
AY             380
HR             380
AR             380
HBP           8410
ABP           8410
Time          7220
AHh           7220
dtype: int64

1. **General Match Data:**
   - `Div`: League Division
   - `Date`: Match Date (dd/mm/yy)
   - `Time`: Match kick-off time
   - `HomeTeam`: Home team name
   - `AwayTeam`: Away team name
   - `FTHG`: Full Time Home Team Goals
   - `FTAG`: Full Time Away Team Goals
   - `FTR`: Full Time Result (H=Home win, D=Draw, A=Away win)
   - `HTHG`: Half Time Home Team Goals
   - `HTAG`: Half Time Away Team Goals
   - `HTR`: Half Time Result (H=Home win, D=Draw, A=Away win)

2. **Match Statistics (if available):**
   - `Attendance`: Crowd attendance
   - `Referee`: Match referee
   - `HS`/`AS`: Home/Away Team Shots
   - `HST`/`AST`: Home/Away Shots on Target
   - `HHW`/`AHW`: Home/Away Hit Woodwork
   - `HC`/`AC`: Home/Away Corners
   - `HF`/`AF`: Home/Away Fouls Committed
   - `HO`/`AO`: Home/Away Offsides
   - `HY`/`AY`: Home/Away Yellow Cards
   - `HR`/`AR`: Home/Away Red Cards

3. describe the data

In [124]:
df.describe()

,FTHG,FTAG,HTHG,HTAG,Attendance,HS,AS,HST,AST,HHW,...,AF,HO,AO,HY,AY,HR,AR,HBP,ABP,AHh
count,9170.000000,9170.000000,9170.000000,9170.000000,759.000000,8790.000000,8790.000000,8790.000000,8790.000000,760.000000,...,8790.000000,760.000000,760.000000,8790.000000,8790.000000,8790.000000,8790.000000,760.000000,760.000000,1950.000000
mean,1.543621,1.175136,0.688441,0.516031,33718.504611,13.562912,10.731741,6.078953,4.755973,0.342105,...,11.807736,3.367105,3.551316,1.444824,1.770648,0.062230,0.084642,15.144737,20.335526,-0.269487
std,1.313082,1.153822,0.837088,0.729849,12108.931821,5.326272,4.666015,3.302774,2.778867,0.608517,...,3.954213,2.421516,2.571250,1.205703,1.280965,0.253087,0.289975,14.590776,15.912700,0.924937
min,0.000000,0.000000,0.000000,0.000000,14651.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.000000
25%,1.000000,0.000000,0.000000,0.000000,24707.000000,10.000000,7.000000,4.000000,3.000000,0.000000,...,9.000000,2.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,10.000000,-0.750000
50%,1.000000,1.000000,0.000000,0.000000,32910.000000,13.000000,10.000000,6.000000,4.000000,0.000000,...,12.000000,3.000000,3.000000,1.000000,2.000000,0.000000,0.000000,10.000000,20.000000,-0.250000
75%,2.000000,2.000000,1.000000,1.000000,39834.000000,17.000000,14.000000,8.000000,6.000000,1.000000,...,14.000000,5.000000,5.000000,2.000000,3.000000,0.000000,0.000000,20.000000,30.000000,0.250000
max,9.000000,9.000000,5.000000,5.000000,67683.000000,39.000000,31.000000,24.000000,20.000000,4.000000,...,29.000000,14.000000,17.000000,7.000000,9.000000,3.000000,2.000000,85.000000,100.000000,2.500000

4. drop unecessary columns

In [125]:
# drop unnecessary columns
# df = df.drop(columns=['Time','FTHG','ABP', 'AHh' ,'FTAG', 'HTHG', 'HTAG', 'HTR','Attendance','Referee','HS','AS','HST','AST','HHW','AHW','HC','AC','HF','AF','HO','AO','HY','AY','HR','AR','HBP',])

# remain with the following columns:
columns_to_keep = ['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTR', 'FTHG', 'FTAG']
df = df[columns_to_keep]


# check the data
print(df.head())

  Div        Date       HomeTeam     AwayTeam FTR  FTHG  FTAG
0  E0  1999-08-07        Arsenal    Leicester   H   2.0   1.0
1  E0  1999-08-07        Chelsea   Sunderland   H   4.0   0.0
2  E0  1999-08-07       Coventry  Southampton   A   0.0   1.0
3  E0  1999-08-07          Leeds        Derby   D   0.0   0.0
4  E0  1999-08-07  Middlesbrough     Bradford   A   0.0   1.0

In [126]:
# check the data description
print(df.describe())

              FTHG         FTAG
count  9170.000000  9170.000000
mean      1.543621     1.175136
std       1.313082     1.153822
min       0.000000     0.000000
25%       1.000000     0.000000
50%       1.000000     1.000000
75%       2.000000     2.000000
max       9.000000     9.000000

In [127]:
# check the data info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9170 entries, 0 to 9169
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Div       9170 non-null   object
 1   Date      9170 non-null   object
 2   HomeTeam  9170 non-null   object
 3   AwayTeam  9170 non-null   object
 4   FTR       9170 non-null   object
 5   FTHG      9170 non-null   float64
 6   FTAG      9170 non-null   float64
dtypes: float64(2), object(5)
memory usage: 501.6+ KB
None

- encode Full Time Result

In [128]:
df['FTR'] = df['FTR'].map({'H': 1, 'D': 0, 'A': -1})
df.head()

  Div        Date       HomeTeam     AwayTeam  FTR  FTHG  FTAG
0  E0  1999-08-07        Arsenal    Leicester    1   2.0   1.0
1  E0  1999-08-07        Chelsea   Sunderland    1   4.0   0.0
2  E0  1999-08-07       Coventry  Southampton   -1   0.0   1.0
3  E0  1999-08-07          Leeds        Derby    0   0.0   0.0
4  E0  1999-08-07  Middlesbrough     Bradford   -1   0.0   1.0

In [129]:
# remove raws that have FTR as null
df = df[df['FTR'].notna()]

# check the data
df.head()

  Div        Date       HomeTeam     AwayTeam  FTR  FTHG  FTAG
0  E0  1999-08-07        Arsenal    Leicester    1   2.0   1.0
1  E0  1999-08-07        Chelsea   Sunderland    1   4.0   0.0
2  E0  1999-08-07       Coventry  Southampton   -1   0.0   1.0
3  E0  1999-08-07          Leeds        Derby    0   0.0   0.0
4  E0  1999-08-07  Middlesbrough     Bradford   -1   0.0   1.0

In [130]:
df.describe()

               FTR         FTHG         FTAG
count  9170.000000  9170.000000  9170.000000
mean      0.169248     1.543621     1.175136
std       0.850944     1.313082     1.153822
min      -1.000000     0.000000     0.000000
25%      -1.000000     1.000000     0.000000
50%       0.000000     1.000000     1.000000
75%       1.000000     2.000000     2.000000
max       1.000000     9.000000     9.000000

### Head to head results for each game

In [131]:
# df['HomeTeamGoalsAVG'] = df.groupby('HomeTeam')['FTHG'].rolling(window = 5).mean().reset_index(0, drop = True)
# df['AwayTeamGoalsAVG'] = df.groupby('AwayTeam')['FTAG'].rolling(window = 5).mean().reset_index(0, drop = True)
# df

# create a function to extract the head to head result
def extract_head_to_head_result(df):
    """Extracts values from 'FTAW' and 'FTHG' columns to create 'head_to_head_result'.

    Args:
        df: The Pandas DataFrame containing the 'FTAW' and 'FTHG' columns.

    Returns:
        A new DataFrame with the added 'head_to_head_result' column.
        If 'FTAW' or 'FTHG' are not present, it returns the original DataFrame unchanged.
    """

    df['h2h_result'] = df.apply(lambda row: f"{row['FTHG']}-{row['FTAG']}", axis=1)
    return df

df = extract_head_to_head_result(df)
df

,Div,Date,HomeTeam,AwayTeam,FTR,FTHG,FTAG,h2h_result
0,E0,1999-08-07,Arsenal,Leicester,1,2.0,1.0,2.0-1.0
1,E0,1999-08-07,Chelsea,Sunderland,1,4.0,0.0,4.0-0.0
2,E0,1999-08-07,Coventry,Southampton,-1,0.0,1.0,0.0-1.0
3,E0,1999-08-07,Leeds,Derby,0,0.0,0.0,0.0-0.0
4,E0,1999-08-07,Middlesbrough,Bradford,-1,0.0,1.0,0.0-1.0
...,...,...,...,...,...,...,...,...
9165,E0,2024-09-21,Southampton,Ipswich,0,1.0,1.0,1.0-1.0
9166,E0,2024-09-21,Tottenham,Brentford,1,3.0,1.0,3.0-1.0
9167,E0,2024-09-21,Crystal Palace,Man United,0,0.0,0.0,0.0-0.0
9168,E0,2024-09-22,Brighton,Nott'm Forest,0,2.0,2.0,2.0-2.0
9169,E0,2024-09-22,Man City,Arsenal,0,2.0,2.0,2.0-2.0

### Team performance metrics

In [132]:
# create a function to calculate the metrics
def calculate_metrics(df, team_name):
    """
    Calculate metrics for a given team.
    """
    metrics = {
        'Team': team_name,
        'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 0},
        'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0},
        'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0},
    }

    # filter matches involving the team (home or away)
    team_matches = df[(df['HomeTeam'] == team_name) | (df['AwayTeam'] == team_name)]
    
    # get the last 5 matches
    last_matches = team_matches.tail(5)
    
    # calculate the metrics
    for _, match in last_matches.iterrows():
        # determine if the team is home or away
        is_home = match['HomeTeam'] == team_name
        
        # full-time result
        if is_home:
            if match['FTR'] == '1':
                metrics['RecentForm']['Wins'] += 1
                metrics['HomePerformance']['Wins'] += 1
            elif match['FTR'] == '0':
                metrics['RecentForm']['Draws'] += 1
                metrics['HomePerformance']['Draws'] += 1
            else:
                metrics['RecentForm']['Losses'] += 1
                metrics['HomePerformance']['Losses'] += 1
        else:
            if match['FTR'] == '1':
                metrics['RecentForm']['Wins'] += 1
                metrics['AwayPerformance']['Wins'] += 1
            elif match['FTR'] == '0':
                metrics['RecentForm']['Draws'] += 1
                metrics['AwayPerformance']['Draws'] += 1
            else:
                metrics['RecentForm']['Losses'] += 1
                metrics['AwayPerformance']['Losses'] += 1

    return metrics

# Example usage:
#df = pd.read_csv('path/to/your/data.csv')
metrics = calculate_metrics(df, 'Liverpool')
metrics

{'Team': 'Liverpool',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 5},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 3},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 2}}

In [133]:
manchester = calculate_metrics(df, 'Manchester United')
manchester

{'Team': 'Manchester United',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0}}

In [134]:

liverpool = calculate_metrics(df, 'Liverpool')
liverpool

{'Team': 'Liverpool',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 5},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 3},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 2}}

In [135]:

chelsea = calculate_metrics(df, 'Chelsea')
chelsea

{'Team': 'Chelsea',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 5},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 2},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 3}}

In [136]:

arsenal = calculate_metrics(df, 'Arsenal')
arsenal

{'Team': 'Arsenal',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 5},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 2},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 3}}

In [137]:

spurs = calculate_metrics(df, 'Tottenham Hotspur')
spurs

{'Team': 'Tottenham Hotspur',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0}}

In [139]:
man_city = calculate_metrics(df, 'Manchester City')
man_city

{'Team': 'Manchester City',
 'RecentForm': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'HomePerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0},
 'AwayPerformance': {'Wins': 0, 'Draws': 0, 'Losses': 0}}